Repository ComposioHQ/composio-js, pull requests merged in 2024-06, with the labels that each got.

#3 Add openAI framework
  examples/demo.ts
  examples/langchain/demo.mjs
  examples/langchain/package.json
  examples/langchain/pnpm-lock.yaml
  examples/openai/demo.mjs
  examples/openai/demo_assistant.mjs
  examples/openai/package.json
  examples/openai/pnpm-lock.yaml
  package.json
  pnpm-lock.yaml
  src/frameworks/openai.ts
  src/index.ts
  src/utils/shared.ts
Labels: enhancement, dependencies, other, Review effort [1-5]: 4

#5 feat: add more support for actions, tags, triggers
  src/frameworks/langchain.ts
  src/index.ts
  src/sdk/base.toolset.ts
  src/sdk/client/services.gen.ts
  src/sdk/client/types.gen.ts
  src/sdk/enums.ts
  src/sdk/index.ts
  src/sdk/models/activeTriggers.ts
  src/sdk/models/apps.ts
  src/sdk/models/connectedAccounts.ts
  src/sdk/models/integrations.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 4

#7 feat: important tag
  package.json
  src/frameworks/langchain.ts
  src/frameworks/openai.ts
  src/sdk/client/types.gen.ts
Labels: enhancement, other, Review effort [1-5]: 3
